### ISSUE TITLE
投稿职业

### ISSUE THREAD

**Issue by Laverist** [TEAM-TONEX/TownOfNewEpic_Xi#14]
随机   附加职业
info:如此多的可能性
职业介绍:将某些职业的技能换为随机概率发动(随机概率)
例如:法官，审判时有x%概率审判成功(概率房主设置)
        豺狼，招募时有x%概率招募成功(概率房主设置)

可设置:
成功概率: 0-100 %
被击杀时将此附加给予给凶手 开关
启用其余设置
───随机击杀冷却 0-180 s

**Comment by Slok7565** [comment]
写这个我容易疯)
