### ISSUE TITLE
投稿职业(2)

### ISSUE THREAD

**Issue by Laverist** [TEAM-TONEX/TownOfNewEpic_Xi#15]
职业名字:没想(船员)
info:你只需要做任务就好了，而内鬼需要思考的就多了
技能:做任务触发，每做一个任务给内鬼不同效果
1.击杀/技能冷却重置
2.下一次击杀失效(通过击杀键使用技能的不计入)
3.随机传送到某个管道
4.固定原地x秒

设置:
对邪恶中立有效果(on/off)
对善良中立有效果(on/off)
固定秒数 1-180 s
单独设置任务数

**Comment by Slok7565** [comment]
可以考虑
