### ISSUE TITLE
PLAY button not working

### ISSUE THREAD

**Issue by 0t3x** [TEAM-TONEX/TownOfNewEpic_Xi#33]
**BUG**
PLAY button on home page not responding

**Steps to reproduce the behavior:**
1. Go to 'Home'
2. Click on 'PLAY button' **this will show nothing**

**Screenshot**
![image](https://github.com/user-attachments/assets/a2912c1f-997b-41c9-b2ed-20a0d3e8b02d)

**Thank You!**

**Comment by Slok7565** [comment]
Thank you for your support. Perhaps you should update Among Us to v2024.8.13
